"""init

Revision ID: 3fd2bba386fa
Revises: 
Create Date: 2026-05-09 10:40:18.857568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd2bba386fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('service_type',
    sa.Column('type_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('service',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('type_id', sa.String(length=32), nullable=False),
    sa.Column('uom', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.provider_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['service_type.type_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('service_parameter_value',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'parameter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_parameter_value')
    op.drop_table('service')
    op.drop_table('service_type')
    op.drop_table('provider')
    # ### end Alembic commands ###
